export const menu = [
  {
    id: 'deluxe_burger',
    name: 'Double Deluxe Burger',
    tagline: 'Signature · House special',
    description: 'Two flame-grilled beef patties stacked with aged cheddar, smoked bacon, caramelised onions and our secret house sauce in a toasted brioche bun.',
    price: 18.9,
    imageUrl: 'assets/images/food_deluxe_burger.jpg',
    cutoutUrl: 'assets/images/cutout_burger.png',
    category: 'burger',
    rating: 4.9,
    reviewCount: 482,
    deliveryMinutes: 20,
    distanceKm: 1.2,
    calories: 780,
    sizes: ['Single', 'Double', 'Triple'],
    isPopular: true
  },
  {
    id: 'salmon_sushi',
    name: 'Salmon Sushi Set',
    tagline: 'Chef’s selection · Fresh daily',
    description: 'A curated set of salmon nigiri and signature rolls prepared with sushi-grade salmon, served with wasabi, pickled ginger and house soy.',
    price: 24.5,
    imageUrl: 'assets/images/food_sushi.jpg',
    cutoutUrl: 'assets/images/cutout_sushi.png',
    category: 'sushi',
    rating: 4.8,
    reviewCount: 311,
    deliveryMinutes: 18,
    distanceKm: 2.1,
    calories: 420,
    sizes: ['8 pcs', '12 pcs', '16 pcs'],
    isPopular: true
  },
  {
    id: 'truffle_fries',
    name: 'Truffle Loaded Fries',
    tagline: 'Crispy · Shareable',
    description: 'Golden hand-cut fries tossed in truffle oil, topped with parmesan, fresh herbs and a creamy garlic aioli on the side.',
    price: 9.9,
    imageUrl: 'assets/images/food_fries.jpg',
    cutoutUrl: 'assets/images/cutout_fries.png',
    category: 'sides',
    rating: 4.7,
    reviewCount: 268,
    deliveryMinutes: 12,
    distanceKm: 1.6,
    calories: 510,
    sizes: ['Regular', 'Large', 'Sharing'],
    isPopular: true
  },
  {
    id: 'cheeseburger',
    name: 'Classic Cheeseburger',
    tagline: 'All-time favourite',
    description: 'A juicy char-grilled beef patty with melted American cheese, crisp lettuce, tomato and pickles in a soft sesame bun.',
    price: 12.5,
    imageUrl: 'assets/images/food_cheeseburger.jpg',
    cutoutUrl: 'assets/images/cutout_burger.png',
    category: 'burger',
    rating: 4.6,
    reviewCount: 540,
    deliveryMinutes: 18,
    distanceKm: 1.4,
    calories: 620,
    sizes: ['Single', 'Double'],
    isPopular: false
  },
  {
    id: 'gourmet_hotdog',
    name: 'Gourmet Hotdog',
    tagline: 'Street-style · Loaded',
    description: 'A premium pork sausage in a brioche roll, topped with fresh herbs, crispy onions and a drizzle of mustard and ketchup.',
    price: 8.5,
    imageUrl: 'assets/images/food_hotdog.jpg',
    cutoutUrl: 'assets/images/cutout_hotdog.png',
    category: 'hotdog',
    rating: 4.5,
    reviewCount: 196,
    deliveryMinutes: 14,
    distanceKm: 1.9,
    calories: 480,
    sizes: ['Regular', 'Footlong'],
    isPopular: false
  },
  {
    id: 'sushi_platter',
    name: 'Dragon Roll Platter',
    tagline: 'Shareable · Premium',
    description: 'An assortment of dragon rolls, maki and nigiri arranged on a sharing board with edamame, pickled vegetables and dipping sauces.',
    price: 32,
    imageUrl: 'assets/images/food_sushi_platter.jpg',
    cutoutUrl: 'assets/images/cutout_bento.png',
    category: 'sushi',
    rating: 4.9,
    reviewCount: 142,
    deliveryMinutes: 22,
    distanceKm: 2.3,
    calories: 690,
    sizes: ['For 2', 'For 4'],
    isPopular: false
  },
  {
    id: 'caesar_salad',
    name: 'Grilled Caesar Salad',
    tagline: 'Fresh · Light',
    description: 'Crisp romaine and baby gem tossed in classic Caesar dressing with parmesan, croutons and tender grilled chicken.',
    price: 11,
    imageUrl: 'assets/images/food_salad.jpg',
    cutoutUrl: 'assets/images/cutout_salad.png',
    category: 'salad',
    rating: 4.4,
    reviewCount: 88,
    deliveryMinutes: 13,
    distanceKm: 1.2,
    calories: 320,
    sizes: ['Regular', 'Large'],
    isPopular: false
  },
  {
    id: 'garden_burger',
    name: 'Garden Stack Burger',
    tagline: 'Fresh greens · Juicy',
    description: 'A beef patty layered with melted mozzarella, fresh tomato, crisp lettuce and onion in a golden sesame bun.',
    price: 13.9,
    imageUrl: 'assets/images/food_garden_burger.jpg',
    cutoutUrl: 'assets/images/cutout_burger.png',
    category: 'burger',
    rating: 4.6,
    reviewCount: 173,
    deliveryMinutes: 17,
    distanceKm: 1.5,
    calories: 650,
    sizes: ['Single', 'Double'],
    isPopular: false
  }
];
